## Preprocessing

In [67]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dla-1-2/m21/lms/starter/charity_data.csv")
application_df

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...,...
34294,996009318,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,996010315,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,996012607,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,996015768,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,996086871,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [68]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE
application_df=application_df.drop(columns=['EIN','NAME'])
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [69]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [70]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
D=application_df['APPLICATION_TYPE'].value_counts()
D

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [71]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = [x for x in D.index if D[x]<528]
application_types_to_replace
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [72]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
F=application_df['CLASSIFICATION'].value_counts()
F

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [73]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#application_df_reduced['CLASSIFICATION'].value_counts() where value_counts()>1
E=application_df['CLASSIFICATION'].value_counts()[application_df['CLASSIFICATION'].value_counts() > 1]
E

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [74]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
classifications_to_replace = [x for x in F.index if F[x]<1883]
classifications_to_replace
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [75]:
# Convert categorical data to numeric with `pd.get_dummies`

X = application_df.drop(columns= 'IS_SUCCESSFUL',axis=1)
X = pd.get_dummies(X)

In [76]:
# Split our preprocessed data into our features and target arrays
y = application_df['IS_SUCCESSFUL'].values
X = X.values
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [77]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
len(X_train[0])

43

## Compile, Train and Evaluate the Model

In [78]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  18
hidden_nodes_layer2 = 10
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))
# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_32 (Dense)            (None, 18)                792

 dense_33 (Dense)            (None, 10)                190

 dense_34 (Dense)            (None, 1)                 11

=================================================================
Total params: 993 (3.88 KB)
Trainable params: 993 (3.88 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [79]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [80]:
from tensorflow.keras.callbacks import ModelCheckpoint

# Define the filepath for saving the model weights
filepath = "model_weights.h5"

# Create a ModelCheckpoint callback
checkpoint = ModelCheckpoint(filepath,
                             monitor='val_loss',  # Monitor validation loss
                             save_weights_only=True,  # Save only the weights
                             save_best_only=False,  # Save every epoch
                             period=5)  # Save every 5 epochs

# Include this callback in your model training
nn.fit(X_train_scaled,y_train,
          epochs=100,
          validation_data=(X_test_scaled,y_test),
          callbacks=[checkpoint])

WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.

Epoch 1/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5867 - accuracy: 0.7072 - val_loss: 0.5640 - val_accuracy: 0.7219
Epoch 2/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5585 - accuracy: 0.7262 - val_loss: 0.5578 - val_accuracy: 0.7307
Epoch 3/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5540 - accuracy: 0.7297 - val_loss: 0.5552 - val_accuracy: 0.7315
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5521 - accuracy: 0.7296 - val_loss: 0.5547 - val_accuracy: 0.7305
Epoch 5/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5505 - accuracy: 0.7311 - val_loss: 0.5547 - val_accuracy: 0.7320
Epoch 6/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5498 - accuracy: 0.7303 - val_loss: 0.5522 - val_accuracy: 0.7296
Epoch 7/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5489 - accuracy: 0.7313 - val_loss: 0.5521 - val_accuracy: 0.7299
Epoch 8/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5481 - accuracy: 0.7321 - val_loss: 0.5542 - val_accuracy: 0.7304
Epoch 9/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5473 - accuracy: 0.7324 - val_loss: 0.5536 - val_accuracy: 0.7307
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5468 - accuracy: 0.7329 - val_loss: 0.5520 - val_accuracy: 0.7300
Epoch 11/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5467 - accuracy: 0.7327 - val_loss: 0.5525 - val_accuracy: 0.7308
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5465 - accuracy: 0.7329 - val_loss: 0.5512 - val_accuracy: 0.7326
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5464 - accuracy: 0.7329 - val_loss: 0.5519 - val_accuracy: 0.7308
Epoch 14/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5454 - accuracy: 0.7352 - val_loss: 0.5519 - val_accuracy: 0.7331
Epoch 15/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5457 - accuracy: 0.7353 - val_loss: 0.5515 - val_accuracy: 0.7317
Epoch 16/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5452 - accuracy: 0.7345 - val_loss: 0.5512 - val_accuracy: 0.7318
Epoch 17/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5451 - accuracy: 0.7345 - val_loss: 0.5516 - val_accuracy: 0.7300
Epoch 18/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5446 - accuracy: 0.7342 - val_loss: 0.5544 - val_accuracy: 0.7301
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5448 - accuracy: 0.7344 - val_loss: 0.5518 - val_accuracy: 0.7301
Epoch 20/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5441 - accuracy: 0.7356 - val_loss: 0.5514 - val_accuracy: 0.7301
Epoch 21/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5443 - accuracy: 0.7347 - val_loss: 0.5510 - val_accuracy: 0.7312
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5442 - accuracy: 0.7357 - val_loss: 0.5517 - val_accuracy: 0.7284
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5440 - accuracy: 0.7347 - val_loss: 0.5508 - val_accuracy: 0.7294
Epoch 24/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5437 - accuracy: 0.7352 - val_loss: 0.5510 - val_accuracy: 0.7301
Epoch 25/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5437 - accuracy: 0.7366 - val_loss: 0.5513 - val_accuracy: 0.7306
Epoch 26/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5435 - accuracy: 0.7362 - val_loss: 0.5514 - val_accuracy: 0.7301
Epoch 27/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5432 - accuracy: 0.7357 - val_loss: 0.5514 - val_accuracy: 0.7292
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5429 - accuracy: 0.7363 - val_loss: 0.5524 - val_accuracy: 0.7296
Epoch 29/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5428 - accuracy: 0.7360 - val_loss: 0.5518 - val_accuracy: 0.7278
Epoch 30/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5428 - accuracy: 0.7360 - val_loss: 0.5521 - val_accuracy: 0.7311
Epoch 31/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5427 - accuracy: 0.7355 - val_loss: 0.5513 - val_accuracy: 0.7317
Epoch 32/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5427 - accuracy: 0.7362 - val_loss: 0.5512 - val_accuracy: 0.7314
Epoch 33/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5424 - accuracy: 0.7361 - val_loss: 0.5507 - val_accuracy: 0.7282
Epoch 34/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5424 - accuracy: 0.7365 - val_loss: 0.5516 - val_accuracy: 0.7300
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7362 - val_loss: 0.5528 - val_accuracy: 0.7300
Epoch 36/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5422 - accuracy: 0.7357 - val_loss: 0.5532 - val_accuracy: 0.7305
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5423 - accuracy: 0.7360 - val_loss: 0.5522 - val_accuracy: 0.7304
Epoch 38/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5418 - accuracy: 0.7361 - val_loss: 0.5524 - val_accuracy: 0.7292
Epoch 39/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5424 - accuracy: 0.7351 - val_loss: 0.5534 - val_accuracy: 0.7279
Epoch 40/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5420 - accuracy: 0.7363 - val_loss: 0.5524 - val_accuracy: 0.7294
Epoch 41/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5419 - accuracy: 0.7358 - val_loss: 0.5529 - val_accuracy: 0.7290
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7355 - val_loss: 0.5521 - val_accuracy: 0.7270
Epoch 43/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5418 - accuracy: 0.7361 - val_loss: 0.5500 - val_accuracy: 0.7306
Epoch 44/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5416 - accuracy: 0.7358 - val_loss: 0.5516 - val_accuracy: 0.7297
Epoch 45/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5418 - accuracy: 0.7357 - val_loss: 0.5518 - val_accuracy: 0.7294
Epoch 46/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5418 - accuracy: 0.7371 - val_loss: 0.5508 - val_accuracy: 0.7292
Epoch 47/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5412 - accuracy: 0.7363 - val_loss: 0.5531 - val_accuracy: 0.7261
Epoch 48/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5413 - accuracy: 0.7361 - val_loss: 0.5530 - val_accuracy: 0.7311
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5415 - accuracy: 0.7367 - val_loss: 0.5516 - val_accuracy: 0.7300
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5413 - accuracy: 0.7362 - val_loss: 0.5515 - val_accuracy: 0.7298
Epoch 51/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5409 - accuracy: 0.7372 - val_loss: 0.5539 - val_accuracy: 0.7306
Epoch 52/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5415 - accuracy: 0.7359 - val_loss: 0.5528 - val_accuracy: 0.7241
Epoch 53/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5412 - accuracy: 0.7367 - val_loss: 0.5512 - val_accuracy: 0.7314
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7369 - val_loss: 0.5516 - val_accuracy: 0.7287
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7365 - val_loss: 0.5549 - val_accuracy: 0.7292
Epoch 56/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5407 - accuracy: 0.7366 - val_loss: 0.5519 - val_accuracy: 0.7279
Epoch 57/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5407 - accuracy: 0.7369 - val_loss: 0.5533 - val_accuracy: 0.7290
Epoch 58/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5407 - accuracy: 0.7370 - val_loss: 0.5521 - val_accuracy: 0.7314
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7368 - val_loss: 0.5516 - val_accuracy: 0.7293
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7365 - val_loss: 0.5524 - val_accuracy: 0.7298
Epoch 61/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5401 - accuracy: 0.7377 - val_loss: 0.5532 - val_accuracy: 0.7297
Epoch 62/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5406 - accuracy: 0.7371 - val_loss: 0.5524 - val_accuracy: 0.7289
Epoch 63/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5404 - accuracy: 0.7375 - val_loss: 0.5523 - val_accuracy: 0.7308
Epoch 64/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5406 - accuracy: 0.7373 - val_loss: 0.5508 - val_accuracy: 0.7321
Epoch 65/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5400 - accuracy: 0.7380 - val_loss: 0.5514 - val_accuracy: 0.7301
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7371 - val_loss: 0.5525 - val_accuracy: 0.7300
Epoch 67/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5404 - accuracy: 0.7368 - val_loss: 0.5533 - val_accuracy: 0.7314
Epoch 68/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5401 - accuracy: 0.7376 - val_loss: 0.5513 - val_accuracy: 0.7313
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7376 - val_loss: 0.5505 - val_accuracy: 0.7317
Epoch 70/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5400 - accuracy: 0.7379 - val_loss: 0.5525 - val_accuracy: 0.7282
Epoch 71/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5402 - accuracy: 0.7380 - val_loss: 0.5508 - val_accuracy: 0.7317
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7389 - val_loss: 0.5531 - val_accuracy: 0.7290
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7374 - val_loss: 0.5512 - val_accuracy: 0.7304
Epoch 74/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5404 - accuracy: 0.7374 - val_loss: 0.5510 - val_accuracy: 0.7310
Epoch 75/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5401 - accuracy: 0.7372 - val_loss: 0.5512 - val_accuracy: 0.7282
Epoch 76/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5401 - accuracy: 0.7369 - val_loss: 0.5516 - val_accuracy: 0.7296
Epoch 77/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5402 - accuracy: 0.7376 - val_loss: 0.5512 - val_accuracy: 0.7299
Epoch 78/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5400 - accuracy: 0.7371 - val_loss: 0.5541 - val_accuracy: 0.7285
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7366 - val_loss: 0.5502 - val_accuracy: 0.7307
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7371 - val_loss: 0.5522 - val_accuracy: 0.7305
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7370 - val_loss: 0.5509 - val_accuracy: 0.7307
Epoch 82/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5395 - accuracy: 0.7378 - val_loss: 0.5523 - val_accuracy: 0.7294
Epoch 83/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5397 - accuracy: 0.7374 - val_loss: 0.5520 - val_accuracy: 0.7293
Epoch 84/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5398 - accuracy: 0.7369 - val_loss: 0.5522 - val_accuracy: 0.7283
Epoch 85/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5397 - accuracy: 0.7374 - val_loss: 0.5524 - val_accuracy: 0.7307
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5393 - accuracy: 0.7385 - val_loss: 0.5523 - val_accuracy: 0.7276
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7381 - val_loss: 0.5509 - val_accuracy: 0.7299
Epoch 88/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5397 - accuracy: 0.7372 - val_loss: 0.5510 - val_accuracy: 0.7303
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7376 - val_loss: 0.5522 - val_accuracy: 0.7287
Epoch 90/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5397 - accuracy: 0.7381 - val_loss: 0.5524 - val_accuracy: 0.7296
Epoch 91/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5397 - accuracy: 0.7373 - val_loss: 0.5525 - val_accuracy: 0.7307
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7378 - val_loss: 0.5525 - val_accuracy: 0.7313
Epoch 93/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5396 - accuracy: 0.7377 - val_loss: 0.5520 - val_accuracy: 0.7291
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7382 - val_loss: 0.5531 - val_accuracy: 0.7289
Epoch 95/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5397 - accuracy: 0.7375 - val_loss: 0.5524 - val_accuracy: 0.7296
Epoch 96/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5393 - accuracy: 0.7379 - val_loss: 0.5518 - val_accuracy: 0.7300
Epoch 97/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5394 - accuracy: 0.7378 - val_loss: 0.5522 - val_accuracy: 0.7311
Epoch 98/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5396 - accuracy: 0.7367 - val_loss: 0.5515 - val_accuracy: 0.7296
Epoch 99/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5392 - accuracy: 0.7356 - val_loss: 0.5538 - val_accuracy: 0.7294
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7377 - val_loss: 0.5515 - val_accuracy: 0.7303

In [81]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5515 - accuracy: 0.7303 - 540ms/epoch - 2ms/step
Loss: 0.5515245795249939, Accuracy: 0.7302623987197876

In [82]:
# Export our model to HDF5 file
from tensorflow.keras.models import load_model
nn.save("AlphabetSoupCharity.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(